name: unhook
description: "A simple app that helps you break free from endless scrolling by setting limits, blocking distractions, and reclaiming your time."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  android_package_manager: ^0.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.13
  intl: ^0.19.0
  usage_stats: ^1.2.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default-icon.png
    - assets/lock-icon.png